In [85]:
import numpy as np
import pandas as pd

In [2]:
arr = np.append(0,26)

In [14]:
arr = np.arange(1,26)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [8]:
arr = np.append(0,26)

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [16]:
arr = np.reshape(5,5)

ValueError: cannot reshape array of size 1 into shape (5,)

In [17]:
np.shape(arr)

(25,)

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [34]:
arr = arr.reshape((5,5))

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
arr[:2,:2]

array([[1, 2],
       [6, 7]])

In [37]:
arr.min()

1

In [38]:
arr.max()

25

In [40]:
a = np.random.randn(25)

In [41]:
a

array([-0.55863241,  0.40657596, -2.54287695,  1.66038109, -0.23708532,
        1.15754224,  0.66730982, -0.83308101, -0.38483319, -0.94125464,
        0.45386749,  0.02016476,  0.94605358, -0.02528018, -0.7601702 ,
       -1.1319176 ,  0.40415797,  0.04931289,  0.02111507, -0.25746592,
       -0.6216186 ,  1.65026649, -1.03684666, -0.22214101, -0.14045358])

In [45]:
a

array([-0.55863241,  0.40657596, -2.54287695,  1.66038109, -0.23708532,
        1.15754224,  0.66730982, -0.83308101, -0.38483319, -0.94125464,
        0.45386749,  0.02016476,  0.94605358, -0.02528018, -0.7601702 ,
       -1.1319176 ,  0.40415797,  0.04931289,  0.02111507, -0.25746592,
       -0.6216186 ,  1.65026649, -1.03684666, -0.22214101, -0.14045358])

In [46]:
a.shape

(25,)

In [48]:
a = a.reshape((5,5))

In [49]:
a

array([[-0.55863241,  0.40657596, -2.54287695,  1.66038109, -0.23708532],
       [ 1.15754224,  0.66730982, -0.83308101, -0.38483319, -0.94125464],
       [ 0.45386749,  0.02016476,  0.94605358, -0.02528018, -0.7601702 ],
       [-1.1319176 ,  0.40415797,  0.04931289,  0.02111507, -0.25746592],
       [-0.6216186 ,  1.65026649, -1.03684666, -0.22214101, -0.14045358]])

In [50]:
a.max()

1.660381090471233

In [51]:
a.argmax()

3

In [52]:
a.argmin()

2

In [53]:
a[:1,1:4]

array([[ 0.40657596, -2.54287695,  1.66038109]])

In [55]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [59]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [60]:
np.zeros(5)*10

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [62]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
are = np.ones(50).reshape((5,10))

In [64]:
are

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
are.argmax()

0

In [66]:
are.max()

1.0

In [67]:
np.sin(are)

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
        0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
        0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
        0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
        0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098,
        0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [68]:
are = are + arr

ValueError: operands could not be broadcast together with shapes (5,10) (5,5) 

In [69]:
are


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
are = are[0:5,0:5]

In [73]:
are

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
are = are + arr

In [75]:
are

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

In [77]:
are.shape

(5, 5)

In [78]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

ModuleNotFoundError: No module named 'panda'

In [87]:
type(pd)

module

In [109]:
minha_lista = np.arange(0,5)

In [111]:
minha_lista

array([0, 1, 2, 3, 4])

In [112]:
index = ('A B C D E').split()
index

['A', 'B', 'C', 'D', 'E']

In [113]:
serie = pd.Series(data=minha_lista, index=index)

In [108]:
type(serie)

pandas.core.series.Series

In [114]:
serie

A    0
B    1
C    2
D    3
E    4
dtype: int32

In [122]:
minha_lista2 = np.arange(5,10)

In [119]:
serie

A    0
B    1
C    2
D    3
E    4
dtype: int32

In [120]:
serie2

array([5, 6, 7, 8, 9])

In [130]:
index2 = ('A B C D E').split()

In [131]:
serie = pd.Series(data=minha_lista2,index=index2)

In [132]:
serie + serie2

A    10
B    12
C    14
D    16
E    18
dtype: int32

In [133]:
serie

A    5
B    6
C    7
D    8
E    9
dtype: int32

In [137]:
serie2

array([5, 6, 7, 8, 9])

In [139]:
np.random.randn(26)

array([-0.31278019,  0.21907426,  0.68058525,  1.03682347, -0.6876197 ,
        0.86819684,  2.61652315,  0.80444655, -1.22229763,  0.2044632 ,
       -0.49902745,  0.27553052,  0.17861221,  0.44574747, -1.10255549,
       -0.47481246, -0.2219564 , -1.49902169,  0.17231426,  0.21913209,
        0.1155833 ,  1.47615822, -1.1028308 , -0.78502192,  0.0971235 ,
        0.40389125])

In [141]:
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='A B C D'.split())

In [142]:
df

A         B         C         D
A -1.297641 -0.261832 -0.640755  0.014643
B  0.149272  1.630782  1.141625 -0.665491
C -0.363251 -0.193316 -1.066405 -0.382408
D  0.434574  0.101531  0.505512  1.782897
E -0.260882  0.926033 -2.650836  0.930143

In [151]:
df['F'] = df['B'] + df['A']

In [152]:
df

A         B         C         D         F
A -1.297641 -0.261832 -0.640755  0.014643 -1.559473
B  0.149272  1.630782  1.141625 -0.665491  1.780054
C -0.363251 -0.193316 -1.066405 -0.382408 -0.556567
D  0.434574  0.101531  0.505512  1.782897  0.536104
E -0.260882  0.926033 -2.650836  0.930143  0.665150

In [159]:
df.drop('F',axis=1,inplace=True)

In [160]:
df

A         B         C         D
A -1.297641 -0.261832 -0.640755  0.014643
B  0.149272  1.630782  1.141625 -0.665491
C -0.363251 -0.193316 -1.066405 -0.382408
D  0.434574  0.101531  0.505512  1.782897
E -0.260882  0.926033 -2.650836  0.930143

In [162]:
df.loc['A':'C','B':'D']

B         C         D
A -0.261832 -0.640755  0.014643
B  1.630782  1.141625 -0.665491
C -0.193316 -1.066405 -0.382408

In [166]:
df.iloc[0:1,1:]

B         C         D
A -0.261832 -0.640755  0.014643

In [167]:
df

A         B         C         D
A -1.297641 -0.261832 -0.640755  0.014643
B  0.149272  1.630782  1.141625 -0.665491
C -0.363251 -0.193316 -1.066405 -0.382408
D  0.434574  0.101531  0.505512  1.782897
E -0.260882  0.926033 -2.650836  0.930143

In [168]:
bol = df > 0

In [169]:
bol

A      B      C      D
A  False  False  False   True
B   True   True   True  False
C  False  False  False  False
D   True   True   True   True
E  False   True  False   True

In [170]:
df[bol]

A         B         C         D
A       NaN       NaN       NaN  0.014643
B  0.149272  1.630782  1.141625       NaN
C       NaN       NaN       NaN       NaN
D  0.434574  0.101531  0.505512  1.782897
E       NaN  0.926033       NaN  0.930143

In [178]:
df[df['B']>0]

A         B         C         D
B  0.149272  1.630782  1.141625 -0.665491
D  0.434574  0.101531  0.505512  1.782897
E -0.260882  0.926033 -2.650836  0.930143