In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\JOSE\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
minha_lista = [1,2,3]

In [4]:
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista)

array([1, 2, 3])

In [8]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
arr = np.zeros(3)

In [14]:
arr

array([0., 0., 0.])

In [15]:
 arr = np.zeros((5,5))

In [16]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
 np.linspace(0,10,2)

array([ 0., 10.])

In [19]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.random.rand(5)

array([0.25773716, 0.22963695, 0.96963377, 0.00336186, 0.01914052])

In [22]:
np.random.rand(5) * 100

array([14.72232483, 67.90879538, 36.93678241, 26.85674056, 98.06824541])

In [23]:
np.random.rand(5) * 10

array([6.82249121, 2.79163873, 5.02199021, 2.42012882, 9.01840323])

In [24]:
np.random.rand(10) * 100

array([27.99167487, 86.89811994, 60.92959925, 61.17837355, 85.96349121,
       80.05164545,  3.4089884 , 64.91632552, 86.80150407, 94.5904366 ])

In [25]:
np.random.rand(5,4,3) * 100

array([[[49.74428587, 76.36323888, 74.56949767],
        [ 5.8246753 , 92.22172183, 58.87107637],
        [ 0.15888943, 14.51334878, 46.74800265],
        [11.77172446, 64.66260256, 35.26524042]],

       [[16.49958175, 44.64564839, 54.31503176],
        [98.04064987, 64.45217076, 23.92580156],
        [29.33499877, 65.19319395, 37.16443675],
        [82.99766421,  7.09319425, 28.93761863]],

       [[ 5.24691905, 50.65647701, 55.5095739 ],
        [24.65775438, 20.94158119, 61.17935291],
        [83.88298072,  3.12049379, 60.05008808],
        [89.58625897, 86.52523476, 41.00328632]],

       [[48.82044247, 81.57422506, 48.54354087],
        [15.61958405, 40.69285298, 28.04573982],
        [38.37854274, 39.47012077, 88.90855072],
        [99.60620175, 51.47038653,  7.93357965]],

       [[81.81986315, 53.52559144,  5.18534726],
        [20.69094829, 46.55456425, 58.92470875],
        [96.90754458, 21.73370392,  8.60402029],
        [98.37146585, 23.38346426, 76.33217285]]])

In [26]:
np.random.randn(4)

array([-0.95232188,  0.34923423,  0.41261596, -0.54084322])

In [27]:
np.random.randint(0,100,10)

array([96, 74, 14, 36, 97, 36,  9, 72, 81, 67])

In [28]:
np.round(np.random.rand(5)*100,0)

array([ 4.,  8., 85., 81., 87.])

In [29]:
arr = np.random.rand(25)

In [30]:
arr

array([0.55441951, 0.38513088, 0.42327873, 0.92091001, 0.42026857,
       0.08555602, 0.95688349, 0.26189961, 0.12209958, 0.42317534,
       0.24452918, 0.50394477, 0.05665987, 0.66876169, 0.09447239,
       0.17132413, 0.95718118, 0.44566999, 0.01277558, 0.52059413,
       0.05299825, 0.46886309, 0.75188534, 0.15461149, 0.69473258])

In [32]:
arr.reshape((5,5))

array([[0.55441951, 0.38513088, 0.42327873, 0.92091001, 0.42026857],
       [0.08555602, 0.95688349, 0.26189961, 0.12209958, 0.42317534],
       [0.24452918, 0.50394477, 0.05665987, 0.66876169, 0.09447239],
       [0.17132413, 0.95718118, 0.44566999, 0.01277558, 0.52059413],
       [0.05299825, 0.46886309, 0.75188534, 0.15461149, 0.69473258]])

In [34]:
ARR

NameError: name 'ARR' is not defined

In [35]:
arr

array([0.55441951, 0.38513088, 0.42327873, 0.92091001, 0.42026857,
       0.08555602, 0.95688349, 0.26189961, 0.12209958, 0.42317534,
       0.24452918, 0.50394477, 0.05665987, 0.66876169, 0.09447239,
       0.17132413, 0.95718118, 0.44566999, 0.01277558, 0.52059413,
       0.05299825, 0.46886309, 0.75188534, 0.15461149, 0.69473258])

In [36]:
arr.reshape((5,5))

array([[0.55441951, 0.38513088, 0.42327873, 0.92091001, 0.42026857],
       [0.08555602, 0.95688349, 0.26189961, 0.12209958, 0.42317534],
       [0.24452918, 0.50394477, 0.05665987, 0.66876169, 0.09447239],
       [0.17132413, 0.95718118, 0.44566999, 0.01277558, 0.52059413],
       [0.05299825, 0.46886309, 0.75188534, 0.15461149, 0.69473258]])

In [37]:
arr = arr.reshape((5,5))

In [40]:
arr.shape

(5, 5)

In [41]:
arr.max()

0.9571811774720658

In [42]:
arr.argmax()

16